pkg/health/health.go, pkg/health/health_argo.go, pkg/health/health_test.go, pkg/health/testdata/argo-application-healthy.yaml, pkg/health/testdata/argo-application-missing.yaml
=> feat: health check for argo applications

.github/workflows/release.yml, pkg/health/health_aws.go, pkg/health/health_aws_test.go
resolves: https://github.com/flanksource/is-healthy/issues/28
=> feat: add status/ready for aws resources

pkg/health/health.go, pkg/health/health_namespace.go, pkg/health/health_pod.go, pkg/health/health_test.go
resolves: https://github.com/flanksource/is-healthy/issues/30
=> fix: use "Terminating" instead of "Deleteting" for k8s health

pkg/health/health_node.go
resolves: https://github.com/flanksource/is-healthy/issues/32
=> feat: unschedulable node health check

events/severity.go
resolves: https://github.com/flanksource/is-healthy/issues/34
=> feat: add GetEventSeverity() to get event severity

pkg/health/health_pod.go, pkg/health/health_test.go, pkg/health/testdata/pod-init-container-fail.yaml
resolves: https://github.com/flanksource/is-healthy/issues/36
=> fix: check init container status when pod is pending

pkg/health/health.go, pkg/health/health_pod.go, pkg/health/health_statefulset.go, pkg/health/statusMap.yaml
resolves: https://github.com/flanksource/is-healthy/issues/39
=> fix: improve health checks for kustomization, Pod & statefulset

pkg/health/health.go, pkg/health/health_test.go, pkg/health/statusMap.yaml, pkg/health/testdata/flux-helmrelease-upgradefailed.yaml
resolve: https://github.com/flanksource/is-healthy/issues/41
=> fix: helm release prioritize upgrade failed over reconcile progressing

pkg/health/health_pod.go, pkg/health/health_test.go, pkg/health/testdata/pod-deletion.yaml, pkg/health/testdata/pod-terminating.yaml
resolves: https://github.com/flanksource/is-healthy/issues/60
=> feat: pod stuck in "terminating" for > 15m

pkg/health/health_pod.go, pkg/health/health_test.go, pkg/health/testdata/pod-high-restart-count.yaml, pkg/health/testdata/pod-old-restarts.yaml
resolves: https://github.com/flanksource/is-healthy/issues/70
=> feat: detect frequently restarting pods

pkg/health/health_pod.go, pkg/health/health_test.go, pkg/health/testdata/pod-not-ready-but-container-ready.yaml, pkg/health/testdata/pod-not-ready-container-not-ready.yaml, pkg/health/testdata/pod-ready-container-terminated.yaml
resolves: https://github.com/flanksource/is-healthy/issues/72
=> feat: pod health | restart loop & not ready

pkg/health/health_node.go
resolves: https://github.com/flanksource/is-healthy/issues/80
=> fix: node health error

pkg/health/health_test.go, pkg/health/statusMap.yaml, pkg/health/testdata/kustomization-reconciliation-failed.yaml
resolves: https://github.com/flanksource/is-healthy/issues/88
=> feat: reconciliation failed kustomization health check

pkg/health/health_test.go, pkg/health/status.go, pkg/health/statusMap.yaml, pkg/health/testdata/kustomization-reconciliation-failed-2.yaml
resolves: https://github.com/flanksource/is-healthy/issues/104
=> fix: kustomization health

pkg/health/health_pod.go, pkg/health/health_test.go, pkg/health/testdata/pod-crashloop-pending.yaml
resolves: https://github.com/flanksource/is-healthy/issues/107
=> fix: crashlooping pod should be unhealthy

pkg/health/health_deployment.go, pkg/health/health_replicaset.go, pkg/health/health_statefulset.go
resolves: https://github.com/flanksource/is-healthy/issues/117
=> feat: initial delay seconds support on deployment, replicaset & STS

.github/workflows/lint.yml, Makefile, main.go, pkg/health/health.go, pkg/health/health_argo.go, pkg/health/health_aws.go, pkg/health/health_cert_manager.go, pkg/health/health_cronjob.go, pkg/health/health_daemonset.go, pkg/health/health_deployment.go, pkg/health/health_hpa.go, pkg/health/health_job.go, pkg/health/health_pod.go, pkg/health/health_replicaset.go, pkg/health/health_statefulset.go, pkg/health/health_test.go, pkg/health/status.go, pkg/health/utils.go, pkg/lua/custom_actions_test.go, pkg/lua/lua.go, pkg/lua/lua_test.go, pkg/lua/oslib_safe.go, pkg/lua/resources.go
=> chore: run golines & gofumpt

pkg/health/health.go, pkg/health/health_flanksource.go
related: https://github.com/flanksource/mission-control/issues/1665
=> feat: Canary health check

pkg/health/health.go, pkg/health/health_flanksource.go
Fixes: https://github.com/flanksource/is-healthy/issues/148
=> feat: health func for notification crd

pkg/health/health_flanksource.go
=> feat: on canary health, set uptime

pkg/health/health_fixtures_test.go, pkg/health/health_flanksource.go, pkg/health/health_test.go, pkg/health/testdata/Kubernetes/MissionControl/scrapeConfig-cron-schedule.yaml, pkg/health/testdata/Kubernetes/MissionControl/scrapeConfig-minor-delay.yaml
resolves: https://github.com/flanksource/is-healthy/issues/167
=> fix: scrapeconfig stale check when fix-time cron is used

pkg/health/health_fixtures_test.go, pkg/health/health_flanksource.go, pkg/health/testdata/Kubernetes/MissionControl/notification-last-failed-a-while-ago.yaml, pkg/health/testdata/Kubernetes/MissionControl/notification-last-failed-recently.yaml, pkg/health/testdata/Kubernetes/MissionControl/notification-with-error.yaml
resolves: https://github.com/flanksource/is-healthy/issues/165
=> feat: notification health

pkg/health/health.go, pkg/health/health_fixtures_test.go, pkg/health/health_flanksource.go, pkg/health/testdata/Kubernetes/MissionControl/canary-healthy.yaml, pkg/health/testdata/Kubernetes/MissionControl/canary-unhealthy.yaml
* large error messages were set as status
=> fix: canary health. Limit status

.github/workflows/lint.yml, .gitignore, Makefile, pkg/health/health.go, pkg/health/health_fixtures_test.go, pkg/health/health_gcp.go, pkg/health/health_test.go, pkg/health/status_name.go, pkg/health/testdata/GCP/Compute/Disk/ready.yaml, pkg/health/testdata/GCP/Compute/InstanceGroupManager/scaled-to-zero.yaml, pkg/health/testdata/GCP/Compute/InstanceGroupManager/stable.yaml, pkg/health/testdata/GCP/Sqladmin/Instance/ready.yaml, pkg/health/utils.go
related: https://github.com/flanksource/config-db/issues/1533
=> feat: GCP health
